#!/bin/bash

echo "============================="
echo "  Script Cài Windows VM + Ngrok"
echo "============================="

# Token mặc định
DEFAULT_TOKEN="2utY20bwz9o6yzLbgI3Nt2NmyAv_7yHcjpaw13PiEuvoaJXDW"

# Nhập token (Enter = dùng mặc định)
read -p "Nhập token ngrok [mặc định: $DEFAULT_TOKEN]: " NGROK_TOKEN
NGROK_TOKEN=${NGROK_TOKEN:-$DEFAULT_TOKEN}

# Cập nhật hệ thống
sudo apt update

# Cài đặt Docker & unzip
sudo apt install -y docker.io docker-compose unzip wget

# Xử lý containerd lỗi (nếu có)
sudo apt-mark unhold containerd
sudo apt remove -y containerd containerd.io --purge

# Cài đặt lại Docker
sudo apt update
sudo apt install -y docker.io docker-compose

# Bật Docker service
sudo systemctl unmask docker docker.socket containerd.service
sudo systemctl enable docker docker.socket containerd.service
sudo systemctl start docker docker.socket containerd.service

# Tạo thư mục cấu hình
mkdir -p dockercom
cd dockercom

# Tạo file docker-compose cho Windows VM
cat <<EOF > win10.yml
version: '3'
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      USERNAME: "MASTER"
      PASSWORD: "admin@123"
      RAM_SIZE: "30G"
      CPU_CORES: "16"
      DISK_SIZE: "400G"
      DISK2_SIZE: "100G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    stop_grace_period: 2m
    volumes:
      - /home:/storage
EOF

# Chạy Windows VM
sudo docker-compose -f win10.yml up -d

# Cài đặt ngrok
cd ~
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
unzip ngrok-stable-linux-amd64.zip
sudo mv ngrok /usr/local/bin

# Thêm token ngrok
ngrok authtoken $NGROK_TOKEN

# Chạy ngrok cho RDP và noVNC (nền)
ngrok tcp 3389 > ngrok_rdp.log &
ngrok http 8006 > ngrok_vnc.log &

# Chờ vài giây cho ngrok tạo link
sleep 8

echo "============================="
echo "   Link kết nối RDP và noVNC"
echo "============================="
echo "RDP:"
grep -o 'tcp://[0-9a-zA-Z\.\:]*' ngrok_rdp.log
echo ""
echo "noVNC:"
grep -o 'https://[0-9a-zA-Z\-]*\.ngrok.io' ngrok_vnc.log
echo "============================="
